-- MySQL Script generated by MySQL Workbench
-- 06/11/16 20:26:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teteio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `teteio` ;

-- -----------------------------------------------------
-- Schema teteio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teteio` DEFAULT CHARACTER SET utf8 ;
USE `teteio` ;

-- -----------------------------------------------------
-- Table `teteio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`user` ;

CREATE TABLE IF NOT EXISTS `teteio`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(120) NOT NULL COMMENT '密码',
  `nickname` VARCHAR(45) NOT NULL COMMENT '昵称',
  `email` VARCHAR(45) NOT NULL COMMENT '邮箱',
  `avatar` VARCHAR(255) NOT NULL COMMENT '头像',
  `desc` VARCHAR(45) NOT NULL COMMENT '描述',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teteio`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`category` ;

CREATE TABLE IF NOT EXISTS `teteio`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teteio`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`post` ;

CREATE TABLE IF NOT EXISTS `teteio`.`post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL COMMENT '发布者ID',
  `category_id` INT NOT NULL COMMENT '类别ID',
  `title` VARCHAR(255) NOT NULL COMMENT '标题',
  `content` LONGTEXT NOT NULL COMMENT '内容',
  `excerpt` LONGTEXT NOT NULL COMMENT '摘要',
  `views` INT NOT NULL COMMENT '浏览次数',
  `tags` TEXT NOT NULL,
  `comment_num` INT NOT NULL COMMENT '评论数',
  `attachment_num` INT NOT NULL COMMENT '附件数量',
  `publish` TINYINT NOT NULL COMMENT '是否发布，0未发布，1发布',
  `edit_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '编辑的时间',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_post_user_idx` (`user_id` ASC),
  INDEX `fk_post_category1_idx` (`category_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `teteio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `teteio`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teteio`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`config` ;

CREATE TABLE IF NOT EXISTS `teteio`.`config` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL COMMENT '配置的key',
  `value` TEXT NOT NULL COMMENT '配置的值',
  `name` VARCHAR(45) NOT NULL COMMENT '配置名称',
  `desc` VARCHAR(255) NOT NULL COMMENT '配置的描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teteio`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`tag` ;

CREATE TABLE IF NOT EXISTS `teteio`.`tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teteio`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`attachment` ;

CREATE TABLE IF NOT EXISTS `teteio`.`attachment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL COMMENT '文件名',
  `path` VARCHAR(500) NOT NULL COMMENT '路劲',
  `size` INT NOT NULL COMMENT '文件大小',
  `image` TINYINT NOT NULL DEFAULT 0 COMMENT '是否是图片0不是，1是图片',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teteio`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`role` ;

CREATE TABLE IF NOT EXISTS `teteio`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `char` VARCHAR(45) NOT NULL COMMENT '角色字符串',
  `name` VARCHAR(45) NOT NULL COMMENT '角色名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teteio`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teteio`.`comment` ;

CREATE TABLE IF NOT EXISTS `teteio`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '回复的ID',
  `poster` VARCHAR(45) NOT NULL COMMENT '评论人',
  `content` TEXT NOT NULL COMMENT '评论内容',
  `email` VARCHAR(45) NOT NULL COMMENT '邮箱',
  `homelink` VARCHAR(45) NOT NULL COMMENT '主页',
  `ip` VARCHAR(45) NOT NULL COMMENT 'IP地址',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `teteio`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `teteio`;
INSERT INTO `teteio`.`user` (`id`, `username`, `password`, `nickname`, `email`, `avatar`, `desc`, `created_at`, `updated_at`) VALUES (1, 'wangte', DEFAULT, '风格独特', 'wangte168@sina.com', DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `teteio`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `teteio`;
INSERT INTO `teteio`.`category` (`id`, `name`) VALUES (1, 'PHP');
INSERT INTO `teteio`.`category` (`id`, `name`) VALUES (2, '前端');
INSERT INTO `teteio`.`category` (`id`, `name`) VALUES (3, 'web架构');
INSERT INTO `teteio`.`category` (`id`, `name`) VALUES (4, 'NetPioneer');
INSERT INTO `teteio`.`category` (`id`, `name`) VALUES (5, '心情');
INSERT INTO `teteio`.`category` (`id`, `name`) VALUES (6, 'JavaScript');

COMMIT;


-- -----------------------------------------------------
-- Data for table `teteio`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `teteio`;
INSERT INTO `teteio`.`role` (`id`, `char`, `name`) VALUES (1, 'admin', '管理员');
INSERT INTO `teteio`.`role` (`id`, `char`, `name`) VALUES (2, 'user', '普通用户');

COMMIT;

